name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 30
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Ruby dependency security analysis
        id: ruby-dep-audit
        run: |
          bundle exec bundle-audit update --quiet
          bundle exec bundle-audit check
