name: Release

on:
  workflow_dispatch:
  pull_request:
  # workflow_dispatch:
  # push:
  #   branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_image:
    name: Build a Docker image
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # tags: infinum-onetimesecret/app:latest
          tags: vrabac/dev:infinfum-onetimesecret-latest
